name: Build & Publish Base Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -  main
  workflow_dispatch:

jobs:
  Build_Base_Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Login to Ali-ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          region-id: cn-hangzhou # 3
          access-key-id: "${{ secrets.ACR_ACCESSKEYID }}"
          access-key-secret: "${{ secrets.ACR_ACCESSKEYSECRET }}"

      - name: Run build Script
        run: |
          cd server-ce/
          sudo make build-base
          sudo make build-community

      - name: Publish Community Image
        if: startsWith( ${{ github.event.commits[0].message }} , "[publish]")
        run: |
          cd server-ce/
          sudo make publish-community
