name: Build & Publish Base Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_Base_Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run build Script
        run: |
          export GITHUB_RUN_ID=${{ github.run_id }}
          echo ${DOCKER_CONFIG}
          cd server-ce/
          make build-base
          make build-community

      - name: Login to Ali-ACR
        uses: aliyun/acr-login@v1
        with:
          region-id: cn-hangzhou
          access-key-id: "${{ secrets.ACR_ACCESSKEYID }}"
          access-key-secret: "${{ secrets.ACR_ACCESSKEYSECRET }}"

      - name: Publish Community Image
        if: startsWith( ${{ github.event.commits[0].message }} , "[publish]")
        run: |
          export tag="$(git rev-parse --short HEAD)-${GITHUB_RUN_ID}"
          export aliyun_tag="registry.cn-hangzhou.aliyuncs.com/byrio/overleaf:${tag}"
          docker push ${aliyun_tag}
